# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Total time
#' @param tab  dataframe with two columns "PIN" and "timestamp"
#' @description function computes total amount of time spent interacting with the app by subtracting timestamp of last entry from timestamp of each PIN
#' @return returns dataframe with two columns: "PIN" and "time". "PIN" is ids of participants, "Time" is amount of time spent on the game in seconds
#' @export
get_total_time <- function(tab) {
    .Call(`_CompPsych_get_total_time`, tab)
}

#' @title Versions of the game in the batch
#' @param tab  dataframe with two columns "PIN" and "Version"
#' @description function extracts all versions of the game that appeared in the current batch
#' @return returns dataframe with two columns: "PIN" and "version". "PIN" is ids of participants, "Version" is version of the game
#' @export
get_total_versions <- function(tab) {
    .Call(`_CompPsych_get_total_versions`, tab)
}

